"""initial_schema

Revision ID: 1637d19cd539
Revises: 
Create Date: 2026-04-07 11:15:44.855099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1637d19cd539'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('async_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_async_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('usage_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_logs_user_id'), ['user_id'], unique=False)

    op.drop_table('profiles')
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.drop_index('idx_credit_transactions_user_id')
        batch_op.create_index(batch_op.f('ix_credit_transactions_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('credit_transactions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_credits', ['user_id'], ['user_id'])

    with op.batch_alter_table('user_credits', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_constraint('user_credits_user_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credits', schema=None) as batch_op:
        batch_op.create_foreign_key('user_credits_user_id_fkey', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
        batch_op.alter_column('credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('credit_transactions_user_id_fkey', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_credit_transactions_user_id'))
        batch_op.create_index('idx_credit_transactions_user_id', ['user_id'], unique=False)
        batch_op.alter_column('reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('gen_random_uuid()'))

    op.create_table('profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credits', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name='profiles_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='profiles_pkey')
    )
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_logs_user_id'))

    op.drop_table('usage_logs')
    with op.batch_alter_table('async_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_async_tasks_user_id'))

    op.drop_table('async_tasks')
    # ### end Alembic commands ###
