"""
Export API — PDF generation for resumes and cover letters.
"""

import io
import logging
from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from typing import Optional

from app.api.deps import get_current_user

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

logger = logging.getLogger(__name__)

router = APIRouter()


class PDFRequest(BaseModel):
    content: str = Field(..., min_length=10)
    title: str = "Skillmate AI Document"
    doc_type: Optional[str] = "resume"  # "resume", "cover_letter", "report"


@router.post("/pdf")
async def export_pdf(
    data: PDFRequest,
    user: dict = Depends(get_current_user),
):
    """Generates a professional PDF from text content."""

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=18,
        spaceAfter=20,
        textColor=HexColor("#1e293b"),
        fontName="Helvetica-Bold",
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=11,
        leading=16,
        spaceAfter=8,
        textColor=HexColor("#334155"),
        fontName="Helvetica",
    )

    section_style = ParagraphStyle(
        "SectionHeader",
        parent=styles["Heading2"],
        fontSize=13,
        spaceBefore=16,
        spaceAfter=8,
        textColor=HexColor("#4f46e5"),
        fontName="Helvetica-Bold",
    )

    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=HexColor("#94a3b8"),
        fontName="Helvetica",
    )

    # Build content
    elements = []

    # Title
    elements.append(Paragraph(data.title, title_style))
    elements.append(Spacer(1, 12))

    # Process content - split by lines and handle sections
    lines = data.content.split("\n")
    for line in lines:
        stripped = line.strip()
        if not stripped:
            elements.append(Spacer(1, 6))
            continue

        # Detect section headers (lines that are ALL CAPS or start with ##)
        if stripped.startswith("##"):
            elements.append(Paragraph(stripped.lstrip("#").strip(), section_style))
        elif stripped.isupper() and len(stripped) < 60:
            elements.append(Paragraph(stripped, section_style))
        elif stripped.startswith("- ") or stripped.startswith("• "):
            bullet_text = f"• {stripped.lstrip('- •').strip()}"
            elements.append(Paragraph(bullet_text, body_style))
        else:
            # Escape HTML special chars for reportlab
            safe_text = stripped.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            elements.append(Paragraph(safe_text, body_style))

    # Footer
    elements.append(Spacer(1, 30))
    elements.append(Paragraph("Generated by Skillmate AI — skillmate.ai", footer_style))

    # Build PDF
    doc.build(elements)
    buffer.seek(0)

    # Sanitize filename
    safe_title = "".join(c for c in data.title if c.isalnum() or c in " _-").strip()
    filename = f"{safe_title or 'Skillmate_Document'}.pdf"

    logger.info(f"PDF exported for user {user.get('id')}: {filename}")

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
        },
    )
