"""
LaTeX Resume Builder API — Convert resume to professional LaTeX (Overleaf-compatible).
=====================================================================================
Uses AI to parse unstructured resume text into structured JSON, then renders
it into a professional ATS-optimized LaTeX template (Jake's Resume format).
"""

import json
import logging
import re
from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel, Field
from typing import Optional, List, Dict
from sqlalchemy.orm import Session

from app.services.ai_service import ai_service
from app.api.deps import get_current_user
from app.core.database import get_db
from app.api.history import save_analysis

logger = logging.getLogger(__name__)

router = APIRouter()


# --- Request / Response Models ---

class LatexResumeRequest(BaseModel):
    resume_text: str = Field(..., min_length=50, description="Raw resume text to convert")
    job_description: Optional[str] = Field(None, description="Optional JD for ATS optimization")
    template: str = Field("jake", description="Template style: jake (default)")


class LatexResumeResponse(BaseModel):
    latex_code: str
    parsed_sections: Dict
    template_used: str
    status: str


# --- LaTeX Escaping ---

def escape_latex(text: str) -> str:
    """Escape special LaTeX characters in user text."""
    if not text:
        return ""
    # Order matters: & must be first, backslash must be handled carefully
    replacements = [
        ('\\', r'\textbackslash{}'),
        ('&', r'\&'),
        ('%', r'\%'),
        ('$', r'\$'),
        ('#', r'\#'),
        ('_', r'\_'),
        ('{', r'\{'),
        ('}', r'\}'),
        ('~', r'\textasciitilde{}'),
        ('^', r'\textasciicircum{}'),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def safe_latex(text: str) -> str:
    """Escape text for LaTeX but preserve intentional LaTeX commands."""
    if not text:
        return ""
    # Only escape the dangerous chars that appear in plain text
    text = text.replace('&', r'\&')
    text = text.replace('%', r'\%')
    text = text.replace('#', r'\#')
    text = text.replace('~', r'\textasciitilde{}')
    return text


# --- LaTeX Template Builder ---

def build_latex_resume(data: Dict) -> str:
    """Build complete LaTeX document from structured resume data."""

    # Extract sections with safe defaults
    personal = data.get("personal_info", {})
    summary = data.get("summary", "")
    education = data.get("education", [])
    experience = data.get("experience", [])
    projects = data.get("projects", [])
    skills = data.get("technical_skills", {})
    certifications = data.get("certifications", [])

    # --- Build document ---
    latex = r"""%-------------------------
% ATS-Optimized Resume — Generated by Skillmate AI
% Based on Jake's Resume Template (ATS-Friendly)
% Compile with: pdflatex or xelatex
% Upload to Overleaf for instant preview
%-------------------------

\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\usepackage{fontawesome5}
\usepackage{multicol}
\setlength{\multicolsep}{-3.0pt}
\setlength{\columnsep}{-1pt}
\input{glyphtounicode}

%----------FONT OPTIONS----------
\pagestyle{fancy}
\fancyhf{}
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

% Adjust margins
\addtolength{\oddsidemargin}{-0.6in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1.19in}
\addtolength{\topmargin}{-.7in}
\addtolength{\textheight}{1.5in}

\urlstyle{same}

\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

% Sections formatting
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large\bfseries
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

% Ensure that generated PDF is machine readable/ATS parsable
\pdfgentounicode=1

%-------------------------
% Custom commands
\newcommand{\resumeItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
  }
}

\newcommand{\classesList}[4]{
    \item\small{
        {#1 #2 #3 #4 \vspace{-2pt}}
  }
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{1.0\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & \textbf{\small #2} \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubSubheading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \textit{\small#1} & \textit{\small #2} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{1.001\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & \textbf{\small #2}\\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubItem}[1]{\resumeItem{#1}\vspace{-4pt}}

\renewcommand\labelitemi{$\vcenter{\hbox{\tiny$\bullet$}}$}
\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}

\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.0in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%


\begin{document}

"""

    # --- HEADING ---
    name = safe_latex(personal.get("name", "Your Name"))
    location = safe_latex(personal.get("location", ""))
    phone = safe_latex(personal.get("phone", ""))
    email = personal.get("email", "")
    linkedin = personal.get("linkedin", "")
    github = personal.get("github", "")
    website = personal.get("website", "")

    latex += r"""%----------HEADING----------
\begin{center}
    {\Huge \scshape """ + name + r"""} \\ \vspace{1pt}
"""
    if location:
        latex += f"    {location} \\\\ \\vspace{{1pt}}\n"

    # Contact line
    contact_parts = []
    if phone:
        contact_parts.append(r"\raisebox{-0.1\height}\faPhone\ " + phone)
    if email:
        contact_parts.append(
            r"\href{mailto:" + email + r"}{\raisebox{-0.2\height}\faEnvelope\  \underline{" + safe_latex(email) + r"}}"
        )
    if linkedin:
        linkedin_display = linkedin.replace("https://", "").replace("http://", "").rstrip("/")
        contact_parts.append(
            r"\href{" + linkedin + r"}{\raisebox{-0.2\height}\faLinkedin\ \underline{" + safe_latex(linkedin_display) + r"}}"
        )
    if github:
        github_display = github.replace("https://", "").replace("http://", "").rstrip("/")
        contact_parts.append(
            r"\href{" + github + r"}{\raisebox{-0.2\height}\faGithub\ \underline{" + safe_latex(github_display) + r"}}"
        )
    if website:
        website_display = website.replace("https://", "").replace("http://", "").rstrip("/")
        contact_parts.append(
            r"\href{" + website + r"}{\raisebox{-0.2\height}\faGlobe\ \underline{" + safe_latex(website_display) + r"}}"
        )

    if contact_parts:
        latex += r"    \small " + " ~ \n    ".join(contact_parts) + "\n"

    latex += r"""    \vspace{-8pt}
\end{center}

"""

    # --- SUMMARY ---
    if summary:
        latex += r"""%-----------PROFESSIONAL SUMMARY-----------
\section{Summary}
  \small{""" + safe_latex(summary) + r"""}
  \vspace{-8pt}

"""

    # --- EDUCATION ---
    if education:
        latex += r"""%-----------EDUCATION-----------
\section{Education}
  \resumeSubHeadingListStart
"""
        for edu in education:
            school = safe_latex(edu.get("school", ""))
            dates = safe_latex(edu.get("dates", ""))
            degree = safe_latex(edu.get("degree", ""))
            location_edu = safe_latex(edu.get("location", ""))
            gpa = edu.get("gpa", "")
            coursework = edu.get("coursework", "")

            degree_line = degree
            if gpa:
                degree_line += r" $|$ \textbf{" + safe_latex(gpa) + "}"

            latex += f"    \\resumeSubheading\n"
            latex += f"      {{{school}}}{{{dates}}}\n"
            latex += f"      {{{degree_line}}}{{{location_edu}}}\n"

            if coursework:
                latex += r"      \resumeItemListStart" + "\n"
                latex += r"        \resumeItem{Relevant Coursework: " + safe_latex(coursework) + "}\n"
                latex += r"      \resumeItemListEnd" + "\n"

        latex += r"""  \resumeSubHeadingListEnd
  \vspace{-16pt}

"""

    # --- EXPERIENCE ---
    if experience:
        latex += r"""%-----------EXPERIENCE-----------
\section{Experience}
  \resumeSubHeadingListStart
"""
        for exp in experience:
            title = safe_latex(exp.get("title", ""))
            dates = safe_latex(exp.get("dates", ""))
            company = safe_latex(exp.get("company", ""))
            location_exp = safe_latex(exp.get("location", ""))
            bullets = exp.get("bullets", [])

            latex += f"\n    \\resumeSubheading\n"
            latex += f"      {{{title}}}{{{dates}}}\n"
            latex += f"      {{{company}}}{{{location_exp}}}\n"

            if bullets:
                latex += r"      \resumeItemListStart" + "\n"
                for bullet in bullets:
                    # Preserve \textbf{} patterns the AI might add
                    latex += f"        \\resumeItem{{{safe_latex(bullet)}}}\n"
                latex += r"      \resumeItemListEnd" + "\n"

        latex += r"""
  \resumeSubHeadingListEnd
\vspace{-16pt}

"""

    # --- PROJECTS ---
    if projects:
        latex += r"""%-----------PROJECTS-----------
\section{Projects}
    \resumeSubHeadingListStart
"""
        for proj in projects:
            name_proj = safe_latex(proj.get("name", ""))
            tech_stack = safe_latex(proj.get("tech_stack", ""))
            link = proj.get("link", "")
            link_label = proj.get("link_label", "GitHub")
            bullets = proj.get("bullets", [])

            # Build project heading
            heading = r"\textbf{" + name_proj + "}"
            if tech_stack:
                heading += r" $|$ \emph{\small{" + tech_stack + "}}"
            if link:
                heading += r" $|$ \href{" + link + r"}{\underline{" + safe_latex(link_label) + "}}"

            latex += f"\n      \\resumeProjectHeading\n"
            latex += f"          {{{heading}}}{{}}\n"

            if bullets:
                latex += r"          \resumeItemListStart" + "\n"
                for bullet in bullets:
                    latex += f"            \\resumeItem{{{safe_latex(bullet)}}}\n"
                latex += r"          \resumeItemListEnd" + "\n"
                latex += r"          \vspace{-2pt}" + "\n"

        latex += r"""
    \resumeSubHeadingListEnd
\vspace{-16pt}

"""

    # --- TECHNICAL SKILLS ---
    if skills:
        latex += r"""%-----------TECHNICAL SKILLS-----------
\section{Technical Skills}
 \begin{itemize}[leftmargin=0.15in, label={}]
    \small{\item{
"""
        skill_lines = []
        for category, items in skills.items():
            if isinstance(items, list):
                items_str = ", ".join(items)
            else:
                items_str = str(items)
            skill_lines.append(f"     \\textbf{{{safe_latex(category)}}}{{: {safe_latex(items_str)}}}")

        latex += " \\\\\n".join(skill_lines) + "\n"

        latex += r"""    }}
 \end{itemize}
 \vspace{-16pt}

"""

    # --- CERTIFICATIONS ---
    if certifications:
        latex += r"""%-----------CERTIFICATIONS-----------
\section{Certifications}
 \begin{itemize}[leftmargin=0.15in, label={}]
    \small{\item{
        """
        cert_items = [safe_latex(c) for c in certifications]
        latex += " \\textbullet{}\n        ".join(cert_items)
        latex += r"""
    }}
 \end{itemize}

"""

    # --- END ---
    latex += r"""%-------------------------------------------
\end{document}
"""

    return latex


# --- AI Parsing Prompt ---

PARSE_RESUME_PROMPT = """You are a resume parser. Extract structured data from this resume text and return ONLY valid JSON.

RESUME TEXT:
{resume_text}

{jd_context}

Return this exact JSON structure (fill in what you can find, use empty strings/arrays for missing data):
{{
  "personal_info": {{
    "name": "Full Name",
    "location": "City, State, Country",
    "phone": "+1-234-567-8900",
    "email": "email@example.com",
    "linkedin": "https://linkedin.com/in/username",
    "github": "https://github.com/username",
    "website": ""
  }},
  "summary": "Professional summary paragraph...",
  "education": [
    {{
      "school": "University Name",
      "dates": "2020 -- 2024",
      "degree": "B.Tech in Computer Science",
      "location": "City, State",
      "gpa": "CGPA: 9.0 / 10.0",
      "coursework": "Data Structures, Algorithms, ML, ..."
    }}
  ],
  "experience": [
    {{
      "title": "Job Title",
      "dates": "Jan 2024 -- Present",
      "company": "Company Name",
      "location": "City, Country",
      "bullets": [
        "Accomplished X by implementing Y, resulting in Z improvement.",
        "Led a team of N to deliver project on time."
      ]
    }}
  ],
  "projects": [
    {{
      "name": "Project Name",
      "tech_stack": "Python, React, FastAPI",
      "link": "https://github.com/user/repo",
      "link_label": "GitHub",
      "bullets": [
        "Built a full-stack application that does X with Y% accuracy."
      ]
    }}
  ],
  "technical_skills": {{
    "Languages": ["Python", "JavaScript", "SQL"],
    "Frameworks": ["React", "FastAPI", "TensorFlow"],
    "Tools & Databases": ["Git", "Docker", "PostgreSQL"],
    "Cloud & Platforms": ["AWS", "GCP", "Vercel"]
  }},
  "certifications": [
    "AWS Certified Solutions Architect (2024)",
    "Google Cloud Professional (2023)"
  ]
}}

IMPORTANT RULES:
1. Return ONLY the JSON — no markdown, no explanation, no code fences.
2. Use double dashes (--) for date ranges, e.g. "Jan 2024 -- Present".
3. Keep bullet points impactful with metrics where available.
4. Parse ALL sections you can find. If a section doesn't exist, use empty array/string.
5. For skills, group them into logical categories.
6. Preserve any URLs/links found in the resume.
7. Do NOT invent data — only extract what's actually in the resume text.
"""


# --- Main Endpoint ---

@router.post("/generate", response_model=LatexResumeResponse)
async def generate_latex_resume(
    data: LatexResumeRequest,
    user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Parse resume text and generate professional LaTeX code (Overleaf-compatible)."""

    jd_context = ""
    if data.job_description:
        jd_context = f"JOB DESCRIPTION (optimize resume for this role):\n{data.job_description[:2000]}"

    prompt = PARSE_RESUME_PROMPT.format(
        resume_text=data.resume_text[:6000],
        jd_context=jd_context,
    )

    try:
        # Step 1: AI parses resume into structured JSON
        parsed = await ai_service.generate_json(prompt)

        if not parsed or not parsed.get("personal_info"):
            raise ValueError("AI returned empty or invalid parsed data")

        # Step 2: Build LaTeX from structured data
        latex_code = build_latex_resume(parsed)

        # Step 3: Save to history
        save_analysis(
            db=db,
            user_id=user.get("id"),
            tool_type="latex_resume",
            title=f"LaTeX Resume — {parsed.get('personal_info', {}).get('name', 'Unknown')}",
            input_summary=data.resume_text[:200],
            result_data=json.dumps({
                "latex_code": latex_code[:500] + "...",
                "sections_found": list(parsed.keys()),
            }),
        )

        logger.info(f"LaTeX resume generated for user {user.get('id')}")

        return LatexResumeResponse(
            latex_code=latex_code,
            parsed_sections=parsed,
            template_used=data.template,
            status="success",
        )

    except Exception as e:
        logger.error(f"LaTeX resume generation failed for user {user.get('id')}: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to generate LaTeX resume: {str(e)}")
